### ISSUE TITLE
Change source to parse

### ISSUE THREAD

**Issue by bluenex** [bahamas10/css-color-names#8]
Should we rely on a more reliable source like https://www.w3schools.com/colors/colors_names.asp?

**Comment by Ryan-Shrestha** [comment]
No I suggest to use hex decimal pattern to name the color.

**Comment by bahamas10** [comment]
@Ryan-Shrestha I think @bluenex means to use that link as a source of the data, as opposed to xahlee.info which is used currently in getcolors.sh

https://github.com/bahamas10/css-color-names/blob/master/getcolors.sh

**Comment by bahamas10** [comment]
published in `v1.0.1`

**Comment by bluenex** [comment]
That was fast, cheers!
